version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: dreambus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: dreambus
      MYSQL_USER: app
      MYSQL_PASSWORD: apppw
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped