server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:dreambus}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER:app}
    password: ${DB_PASS:apppw}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: debug
#    org.hibernate.SQL: warn
#    org.springframework.security: info

jwt:
  secret: ${JWT_SECRET:Y0urSup3rL0ngSecr3t-Key_with_symbols_2025!!}
  access-exp-seconds: 3600
  refresh-exp-seconds: 1209600

kakao:
  oauth:
    client-id: a97ec6412ca3f704d9258fe1b0fa8281
    client-secret:
    redirect-uri: kakao028c043da80499d5f5a4091190738ab0://oauth
    token-uri: https://kauth.kakao.com/oauth/token
    userinfo-uri: https://kapi.kakao.com/v2/user/me

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator   # (기본값이지만 명시)
  endpoint:
    health:
      show-details: never
